### PR TITLE
fixes #33

### LINKED ISSUE #33: Unexpected behavior when using multiple conditions
I have spotted something strange when trying to connect multiple conditions with OR operator.

Demonstration of the issue:

XPATH EVALUATOR with default data:

**//*[contains(title, "The") or contains(author, "Evelyn")]**
Returns only 2 items - those which have the word "the" in their title.

**//*[contains(title, "The") or contains(author, "velyn")]**
Surprisingly it works when I delete the first character from the author condition.
All 3 items are returned in this case.

Must be some kind of problem with the regex replace. I will try to locate and fix it.

### PR DESCRIPTION
**Pull request by BlackWiCKED**
This could be a suitable solution for Issue #33 - at least it works in my test environment.

### CODE REVIEW

**Comment by hbi99** [comment]
Good catch...thanks a lot.
I'll grunt the files and create new release in a few hours.

Cheers

**Comment by BlackWiCKED** [comment]
Sure thing, thank you for merging! Keep up the good work! I really find this library useful, it makes my work much easier.

**Comment by hbi99** [comment]
@BlackWiCKED 
Thanks...meanwhile, please pass on the link to this lib/repo.
I think and hope that this lib can help many others as well...I just don't know what I can do to make more developers aware of it.

**Comment by BlackWiCKED** [comment]
If I found your lib, probably others will too. I just entered "search JSON object" into Google, and your site came in top results. I tried other alternatives as well, but this one fits exactly to my needs, so I'm satisfied. It's well documented, nicely presented, easy to use, what else do we need? ;)

Anyways, I will share the link on my social network. Hope it brings you 1-2 newcomers!

**Comment by hbi99** [comment]
Great feedback...thanks a lot. Really :)

**Pull request merged**
