### PR TITLE
Fix for IE11

### PR DESCRIPTION
**Pull request by hguiney**
Addresses #16 (for real this time).

### CODE REVIEW

**Comment by hbi99** [comment]
@hguiney,
Super...I'd merge this but can I suggest that you bump the version in "package.json"?
When done, use "gulp minify" to create dist versions of the lib.

If you dont want to do that, please omit the version number in "dist/defiant.js" and I'll do the version bump myself.

Cheers

**Comment by yanndebelgique** [comment]
waiting for this merge...

**Comment by hbi99** [comment]
I'll clean up and add this code from this pull-request.
But it will not be a merge since there are merge-conflicts.

**Comment by hguiney** [comment]
Sorry for the radio silence. I’ll bump the version number and minify in a new PR to make it a proper merge.

**Comment by hguiney** [comment]
OK, fixed!

**Comment by yanndebelgique** [comment]
Thx!!

Apologies for brevity and typos. Sent from my iPhone

**Comment by hbi99** [comment]
Cool...merging.
@hguiney - can you verify that it all works as you expect?

Thanks in advance

**Pull request merged**
